### ISSUE TITLE
menu selection Settings>User init file does not open init file anymore 

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/packages-swipl-win#15]
I have a  threaded, 64 bits, version 8.5.7-11-g3af9964af running in Windows 10 Pro. Init file is still loaded and consulted

**Comment by xpxaxsxi** [comment]
I am now using 8.5.7-31-g6600d5469
`Settings>GUI preferences ...` does work and opens up preferences in Pce-Emacs for editing
`Settings>User init file ...` does nothing

**Comment by JanWielemaker** [comment]
I cannot reproduce this and recall this was fixed recently.  Please try 8.5.11 and close if this is indeed fixed.
